### ISSUE TITLE
The "exportTrailingSlash" option has been renamed to "trailingSlash".

### ISSUE THREAD

**Issue by fky2015** [IlusionDev/nextjs-sitemap-generator#63]
:tada: Hi, thanks for creating such a helpful plugin.

As coded, you extract the `trailing slash` configuration from the `exportTrailingSlash` property in `next.config.js` (as seen below):

https://github.com/IlusionDev/nextjs-sitemap-generator/blob/359c7a9686ec1d4e0626d2570613c72dbe53a2aa/src/core.ts#L181

But In the newest [Next.js Docs](https://github.com/IlusionDev/nextjs-sitemap-generator/blob/359c7a9686ec1d4e0626d2570613c72dbe53a2aa/src/core.ts#L181), it recommends `trailingSlash` property.

And if you run the Next.js app with `exportTrailingSlash`, a warning will follow:

```bash
Warning: The "exportTrailingSlash" option has been renamed to "trailingSlash". Please update your next.config.js.
```

So if it will be better to extract config from `trailingSlash` instead of `exportTrailingSlash` or both of them?

**Comment by miked-known** [comment]
It looks like the next.config value of "trailingSlash" is being ignored. No trailing slashes are being generated.

I'm running version 1.1.1

**Comment by IlusionDev** [comment]
This is solved in the new version 1.1.2 is now in npm. Thanks!!

**Comment by droplab** [comment]
I upgraded to the latest version (^1.1.3) and have `trailingSlash:true` in my next.config.js and I'm still not seeing the trailing slash generated in the sitemap urls. Am i missing anything here? Thanks!

**Comment by IlusionDev** [comment]
> I upgraded to the latest version (^1.1.3) and have `trailingSlash:true` in my next.config.js and I'm still not seeing the trailing slash generated in the sitemap urls. Am i missing anything here? Thanks!

can you show me your config of sitemap and nextjs?
